services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d demo_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.25" # max 25% of a CPU
          memory: 512M # hard memory limit
        reservations:
          cpus: "0.25" # optional
          memory: 256M

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://demo:demo_pass@db:5432/demo_db
      DEMO_USERNAME: demo
      DEMO_PASSWORD: changeme
      SECRET_KEY: supersecretchangeit
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25" # max 25% of a CPU
          memory: 256M # hard memory limit
        reservations:
          cpus: "0.25" # optional
          memory: 256M

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/log/nginx:/var/log/nginx:rw
    ports:
      - "8080:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25" # max 25% of a CPU
          memory: 256M # hard memory limit
        reservations:
          cpus: "0.25" # optional
          memory: 256M
volumes:
  db_data:
